# Generated by Django 5.1.7 on 2025-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Department',
            field=models.CharField(default='Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='RegistratioNo',
            field=models.CharField(default='0000CE000', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Year',
            field=models.CharField(default='First Year', max_length=100),
        ),
    ]
