# Generated by Django 5.1.7 on 2025-03-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_taskdetail_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='TASK_ASSIGNED_TO',
        ),
    ]
