# Generated by Django 5.1.7 on 2025-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_taskdetail_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='TASK_HOLDER',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
