# Generated by Django 5.2 on 2025-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
