# Generated by Django 5.2 on 2025-04-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='profile_image',
        ),
    ]
