# Generated by Django 5.2 on 2025-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_taskdetail_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
